spring:
  application:
    name: GeorgesServiceExample
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

    profiles.active: local

  datasource:
    url: jdbc:h2:file:/data/demo # file-based storage; no data loss.
    username: george
    password: pA$$w0rd
    driverClassName: org.h2.Driver
  jpa:
    database: default
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console                # console is relative to address and port of demo app.
      settings.trace: false            # prevent trace output
      settings.web-allow-others: false # disable remote access
